Proposed code structure and Bevy 0.7 update
jomala/bevy_screen_diags pull request #14
Opened 2022-04-28 23:33 UTC by jomala

I've made a few changes. These conflict or match with the outstanding PRs somewhat randomly. Apologies if I haven't remembered the previous discussion. Frank comments now on this version though please.
* Text objects remain in place even if the display on them is disabled. This is to allow the calling code to rearrange them, or add more than one, and for that to persist after pause/resume.
* I've kept the only control being through the timer member of the state object. Future versions may not, but expoising this seems usefully flexible for now.

2022-04-29 00:02 UTC, SUPERCILEX commented
I'm not sure I like the idea of keeping the text objects around even if the FPS meter is disabled, but it definitely does make the code simpler.

Can you apply this patch? It:

- Removes unnecessary features
- Fixes a bug requiring a full timeout before the FPS meter is initialized
- Fixes a bug where the FPS meter is updated on every NOT tick instead of every tick (aka 59 times per second)
- Runs cargo fmt and simplifies some stuff

```patch
Index: Cargo.toml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Cargo.toml b/Cargo.toml
--- a/Cargo.toml	(revision ad7d4f1a69ab9e077c970c9e5d20add3d5594f10)
+++ b/Cargo.toml	(date 1651189769832)
@@ -12,4 +12,7 @@
 edition = "2021"
 
 [dependencies]
+bevy = { version = "0.7.0", default-features = false, features = ["render"] }
+
+[dev-dependencies]
 bevy = { version = "0.7.0", default-features = false, features = ["render", "bevy_winit", "x11"] }
Index: src/lib.rs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/lib.rs b/src/lib.rs
--- a/src/lib.rs	(revision ad7d4f1a69ab9e077c970c9e5d20add3d5594f10)
+++ b/src/lib.rs	(date 1651190266772)
@@ -15,10 +15,9 @@
 const FONT_SIZE: f32 = 32.0;
 const FONT_COLOR: Color = Color::RED;
 const UPDATE_INTERVAL: Duration = Duration::from_secs(1);
-const STRING_FORMAT: &'static str = "FPS: ";
-const STRING_INITIAL: &'static str = "FPS: ...";
-const STRING_MISSING: &'static str = "FPS: ???";
-const STRING_DISABLED: &'static str = "";
+
+const STRING_FORMAT: &str = "FPS: ";
+const STRING_MISSING: &str = "FPS: ???";
 
 /// A plugin that draws diagnostics on-screen with Bevy UI.
 ///
@@ -41,12 +40,16 @@
 pub struct ScreenDiagsState {
     /// The timer that triggers a diagnostics reading.
     pub timer: Timer,
+    /// Ignore the timer until we get an FPS reading (which will be the second frame after
+    /// diagnostics are initialized).
+    fps_initialized: bool,
 }
 
 impl Default for ScreenDiagsState {
     fn default() -> Self {
         Self {
             timer: Timer::new(UPDATE_INTERVAL, true),
+            fps_initialized: false,
         }
     }
 }
@@ -62,25 +65,20 @@
 ) {
     if let Some(mut state) = state_resource {
         if state.timer.paused() {
-            // Time is paused so remove text
-            for mut text in text_query.iter_mut() {
-                let value = &mut text.sections[0].value;
-                    value.clear();
-                write!(value, "{}", STRING_DISABLED).unwrap();
-            }
-        } else if !state.timer.tick(time.delta()).just_finished() {
+            // Timer is paused so remove text
+            let mut text = text_query.single_mut();
+            text.sections[0].value.clear();
+        } else if state.timer.tick(time.delta()).just_finished() || !state.fps_initialized {
             let fps_diags = extract_fps(&diagnostics);
-
-            for mut text in text_query.iter_mut() {
-                let value = &mut text.sections[0].value;
-                    value.clear();
+            let mut text = text_query.single_mut();
+            let text = &mut text.sections[0].value;
+            text.clear();
 
-                if let Some(fps) = fps_diags {
-                    write!(value, "{}{:.0}", STRING_FORMAT, fps).unwrap();
-                } else {
-                    value.clear();
-                    write!(value, "{}", STRING_MISSING).unwrap();
-                }
+            if let Some(fps) = fps_diags {
+                state.fps_initialized = true;
+                write!(text, "{}{:.0}", STRING_FORMAT, fps).unwrap();
+            } else {
+                write!(text, "{}", STRING_MISSING).unwrap();
             }
         }
     }
@@ -92,24 +90,19 @@
         .and_then(|fps| fps.average())
 }
 
-fn spawn_text(
-    mut commands: Commands,
-    asset_server: Res<AssetServer>,
-) {
-    let handle = asset_server.load("fonts/screen-diags-font.ttf");
+fn spawn_text(mut commands: Commands, asset_server: Res<AssetServer>) {
+    let font = asset_server.load("fonts/screen-diags-font.ttf");
     commands
         .spawn_bundle(TextBundle {
             text: Text {
-                sections: vec![
-                    TextSection {
-                        value: STRING_INITIAL.to_string(),
-                        style: TextStyle {
-                            font: handle.clone(),
-                            font_size: FONT_SIZE,
-                            color: FONT_COLOR,
-                        },
+                sections: vec![TextSection {
+                    value: String::new(),
+                    style: TextStyle {
+                        font,
+                        font_size: FONT_SIZE,
+                        color: FONT_COLOR,
                     },
-                ],
+                }],
                 ..Default::default()
             },
             ..Default::default()
```

2022-04-29 05:51 UTC, flyingblackshark requested changes

2022-04-29 05:51 UTC, flyingblackshark commented on src/lib.rs
> +const STRING_DISABLED: &'static str = "";
Enum is better than constants maybe?

2022-04-30 14:11 UTC, jomala commented
Thanks, both of you, and especially for the bug spot, @SUPERCILEX. I've not gone with your patch though. I've instead added simple interface functions but left them optional. I've also left in support for multiple instances of the text, because there's little cost to doing so rather than because I think it'll ever be used.

2022-04-30 14:14 UTC, merged